footprint: [[-0.27, -0.27], [0.27, -0.27], [0.27, 0.27], [-0.27, 0.27]]
plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
#robot_radius: ir_of_robot
inflation_radius: 0.27

obstacles:
  observation_sources: laser_scan_sensor 
  laser_scan_sensor: {
    sensor_frame: laser_frame, 
    data_type: LaserScan, 
    topic: scan, 
    marking: true, 
    clearing: true
  }
